// Generated by gencpp from file f110_occgrid/ConvertMapRequest.msg
// DO NOT EDIT!


#ifndef F110_OCCGRID_MESSAGE_CONVERTMAPREQUEST_H
#define F110_OCCGRID_MESSAGE_CONVERTMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f110_occgrid
{
template <class ContainerAllocator>
struct ConvertMapRequest_
{
  typedef ConvertMapRequest_<ContainerAllocator> Type;

  ConvertMapRequest_()
    {
    }
  ConvertMapRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertMapRequest_

typedef ::f110_occgrid::ConvertMapRequest_<std::allocator<void> > ConvertMapRequest;

typedef boost::shared_ptr< ::f110_occgrid::ConvertMapRequest > ConvertMapRequestPtr;
typedef boost::shared_ptr< ::f110_occgrid::ConvertMapRequest const> ConvertMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace f110_occgrid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::f110_occgrid::ConvertMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f110_occgrid/ConvertMapRequest";
  }

  static const char* value(const ::f110_occgrid::ConvertMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::f110_occgrid::ConvertMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f110_occgrid::ConvertMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::f110_occgrid::ConvertMapRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // F110_OCCGRID_MESSAGE_CONVERTMAPREQUEST_H
