// Generated by gencpp from file f110_occgrid/ConvertMap.msg
// DO NOT EDIT!


#ifndef F110_OCCGRID_MESSAGE_CONVERTMAP_H
#define F110_OCCGRID_MESSAGE_CONVERTMAP_H

#include <ros/service_traits.h>


#include <f110_occgrid/ConvertMapRequest.h>
#include <f110_occgrid/ConvertMapResponse.h>


namespace f110_occgrid
{

struct ConvertMap
{

typedef ConvertMapRequest Request;
typedef ConvertMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConvertMap
} // namespace f110_occgrid


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::f110_occgrid::ConvertMap > {
  static const char* value()
  {
    return "b13d2865c5af2a64e6e30ab1b56e1dd5";
  }

  static const char* value(const ::f110_occgrid::ConvertMap&) { return value(); }
};

template<>
struct DataType< ::f110_occgrid::ConvertMap > {
  static const char* value()
  {
    return "f110_occgrid/ConvertMap";
  }

  static const char* value(const ::f110_occgrid::ConvertMap&) { return value(); }
};


// service_traits::MD5Sum< ::f110_occgrid::ConvertMapRequest> should match
// service_traits::MD5Sum< ::f110_occgrid::ConvertMap >
template<>
struct MD5Sum< ::f110_occgrid::ConvertMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::f110_occgrid::ConvertMap >::value();
  }
  static const char* value(const ::f110_occgrid::ConvertMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::f110_occgrid::ConvertMapRequest> should match
// service_traits::DataType< ::f110_occgrid::ConvertMap >
template<>
struct DataType< ::f110_occgrid::ConvertMapRequest>
{
  static const char* value()
  {
    return DataType< ::f110_occgrid::ConvertMap >::value();
  }
  static const char* value(const ::f110_occgrid::ConvertMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::f110_occgrid::ConvertMapResponse> should match
// service_traits::MD5Sum< ::f110_occgrid::ConvertMap >
template<>
struct MD5Sum< ::f110_occgrid::ConvertMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::f110_occgrid::ConvertMap >::value();
  }
  static const char* value(const ::f110_occgrid::ConvertMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::f110_occgrid::ConvertMapResponse> should match
// service_traits::DataType< ::f110_occgrid::ConvertMap >
template<>
struct DataType< ::f110_occgrid::ConvertMapResponse>
{
  static const char* value()
  {
    return DataType< ::f110_occgrid::ConvertMap >::value();
  }
  static const char* value(const ::f110_occgrid::ConvertMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // F110_OCCGRID_MESSAGE_CONVERTMAP_H
