// Generated by gencpp from file beginner_tutorials/SommerDeuxEntsResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTSRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct SommerDeuxEntsResponse_
{
  typedef SommerDeuxEntsResponse_<ContainerAllocator> Type;

  SommerDeuxEntsResponse_()
    : sum(0)  {
    }
  SommerDeuxEntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SommerDeuxEntsResponse_

typedef ::beginner_tutorials::SommerDeuxEntsResponse_<std::allocator<void> > SommerDeuxEntsResponse;

typedef boost::shared_ptr< ::beginner_tutorials::SommerDeuxEntsResponse > SommerDeuxEntsResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::SommerDeuxEntsResponse const> SommerDeuxEntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/SommerDeuxEntsResponse";
  }

  static const char* value(const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SommerDeuxEntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::SommerDeuxEntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTSRESPONSE_H
