// Generated by gencpp from file beginner_tutorials/SommerDeuxEnts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTS_H
#define BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/SommerDeuxEntsRequest.h>
#include <beginner_tutorials/SommerDeuxEntsResponse.h>


namespace beginner_tutorials
{

struct SommerDeuxEnts
{

typedef SommerDeuxEntsRequest Request;
typedef SommerDeuxEntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SommerDeuxEnts
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::SommerDeuxEnts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::SommerDeuxEnts&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::SommerDeuxEnts > {
  static const char* value()
  {
    return "beginner_tutorials/SommerDeuxEnts";
  }

  static const char* value(const ::beginner_tutorials::SommerDeuxEnts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::SommerDeuxEntsRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::SommerDeuxEnts >
template<>
struct MD5Sum< ::beginner_tutorials::SommerDeuxEntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SommerDeuxEnts >::value();
  }
  static const char* value(const ::beginner_tutorials::SommerDeuxEntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SommerDeuxEntsRequest> should match
// service_traits::DataType< ::beginner_tutorials::SommerDeuxEnts >
template<>
struct DataType< ::beginner_tutorials::SommerDeuxEntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SommerDeuxEnts >::value();
  }
  static const char* value(const ::beginner_tutorials::SommerDeuxEntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::SommerDeuxEntsResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::SommerDeuxEnts >
template<>
struct MD5Sum< ::beginner_tutorials::SommerDeuxEntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::SommerDeuxEnts >::value();
  }
  static const char* value(const ::beginner_tutorials::SommerDeuxEntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SommerDeuxEntsResponse> should match
// service_traits::DataType< ::beginner_tutorials::SommerDeuxEnts >
template<>
struct DataType< ::beginner_tutorials::SommerDeuxEntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::SommerDeuxEnts >::value();
  }
  static const char* value(const ::beginner_tutorials::SommerDeuxEntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SOMMERDEUXENTS_H
