set(_CATKIN_CURRENT_PACKAGE "hty_lab3")
set(hty_lab3_VERSION "0.0.0")
set(hty_lab3_MAINTAINER "parallels <parallels@todo.todo>")
set(hty_lab3_PACKAGE_FORMAT "2")
set(hty_lab3_BUILD_DEPENDS "ackermann_msgs" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(hty_lab3_BUILD_EXPORT_DEPENDS "ackermann_msgs" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(hty_lab3_BUILDTOOL_DEPENDS "catkin")
set(hty_lab3_BUILDTOOL_EXPORT_DEPENDS )
set(hty_lab3_EXEC_DEPENDS "ackermann_msgs" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(hty_lab3_RUN_DEPENDS "ackermann_msgs" "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(hty_lab3_TEST_DEPENDS )
set(hty_lab3_DOC_DEPENDS )
set(hty_lab3_URL_WEBSITE "")
set(hty_lab3_URL_BUGTRACKER "")
set(hty_lab3_URL_REPOSITORY "")
set(hty_lab3_DEPRECATED "")